export const glossaryTerms = {
//Test terms
	"mica": "A rock group that shares a translucent, flaky, plate-like structure which reflects and refracts light.",
	"British Colonial Indian": 'In the British Colonial Indian Style Period, "Company style painting, also known as Kampani Kalam, emerged in the late eighteenth century during the British East India Company expansion in India. This hybrid art form combined traditional Indian styles, particularly Mughal and Rajput miniature painting, with European techniques like linear perspective, chiaroscuro, and illusionism." — Delhi Art Gallery',
//TD-IDF Terms
		//tbd
// U.S. Government Agencies
	"AEC": "United States Atomic Energy Commission",
	"BIA": "Bureau of Indian Affairs",
	"BLM": "Bureau of Land Management",
	"BOR": "Bureau of Reclamation",
	"BPA": "Bonneville Power Administration",
	"BR": "Bureau of Reclamation",
	"BSFW": "U.S. Bureau of Sport Fisheries and Wildlife",
	"COE": "Centers of Excellence",
	"CSPS": "Cloud Service Providers (CSPs)",
	"DLAB": "U.S. Department of Labor",
	"DOC": "U.S. Department of Commerce (DOC)",
	"EDA": "U.S. Economic Development Administration",
	"EPA": "U.S. Environmental Protection Agency",
	"ERDA": "U.S. Energy Research and Development Administration",
	"FAA": "U.S. Federal Aviation Administration",
	"FDA": "U.S. Food and Drug Administration",
	"FHWA": "U.S. Federal Highway Administration",
	"FPC": "U.S. Federal Privacy Council",
	"FRA": "U.S. Federal Railroad Administration",
	"FS": "U.S. Forest Service",
	"FWS": "U.S. Fish and Wildlife Service",
	"GSA": "U.S. General Services Administration",
	"HUD": "U.S. Department of HoU.S.ing and Urban Development",
	"ICC": "U.S. Interstate Commerce Commission",
	"LEAA": "Law Enforcement Assistance Administration",
	"MARAD": "U.S. Maritime Administration",
	"NASA": "U.S. National Aeronautics and Space Administration",
	"NHTSA": "U.S. National Highway Traffic Safety Administration",
	"NOAA": "U.S.  National Oceanic and Atmospheric Administration",
	"NPS": "U.S. National Parks Service",
	"NRC": "U.S. Nuclear Regulatory Commission",
	"NSF": "U.S. National Science Foundation",
	"REA": "U.S. Rural Electrification Administration",
	"STAT": "U.S. Department of State",
	"STATE": "U.S. Department of State",
	"TVA": "Tennessee Valley Authority",
	"UMTA": "U.S. Urban Mass Transportation Administration",
	"USAF": "United States Air Force",
	"USN": "United States Navy",
	"USPS": "United States Postal Service"
};
